###
GET http://localhost:3000

###
GET http://localhost:3000/post

###
GET http://localhost:3000/post?sender=some+one+1

###
GET http://localhost:3000/post/635a60b2b900c4a44b25ab43

###
POST  http://localhost:3000/post
Content-Type:  application/json

{
    "message": "This is a test message",
    "sender": "some one 2"
}